export const AWS_ACCOUNT_ID = '262115391162'
export const REGION = 'ap-northeast-1'
export const AWS_GITHUB_TRIGGER_STACK_NAME = 'GithubTriggerStack'
export const AWS_COMMON_SERVICE_STACK_NAME = 'CommonServiceStack'
export const AWS_EXPORT_GITHUB_TRIGGER_PIPELINE_ROLE_ARN_KEY = 'exportGithubTriggerPipelineRoleArn'
export const AWS_EXPORT_GITHUB_TRIGGER_CODEBUILD_ROLE_ARN_KEY = 'exportGithubTriggerCodeBuildRoleArn'
export const AWS_EXPORT_GITHUB_TRIGGER_PIPELINE_ARTIFACT_BUCKET_NAME_KEY =
  'exportGithubTriggerPipelineArtifactBucketName'
export const AWS_EXPORT_SOURCE_CODE_BUCKET_NAME_KEY = 'exportSourceCodeBucketName'
export const AWS_EXPORT_CLOUDFRONT_DISTRIBUTION_ID_KEY = 'exportCloudFrontDistributionId'
export const AWS_EXPORT_INVALIDATE_CLOUDFRONT_CACHE_LAMBDA_NAME_KEY = 'exportInvalidateCloudFrontCacheLambdaName'
export const OWNER_NAME = 'muratariku0903'
export const REPOSITORY_NAME = 'flutter_todo'
export const SECRET_GITHUB_TOKEN_NAME = 'github-pipeline-token'
export const SECRET_GITHUB_TOKEN_KEY = 'github-token'
export const GITHUB_CONNECTION_ARN_SSM_KEY = 'todo_github_connectionarn'
