version: 0.2

phases:
  install:
    commands:
      # - echo "Installing Flutter..."
      # - git clone https://github.com/flutter/flutter.git -b stable
      # - export PATH="$PATH:`pwd`/flutter/bin"
      # - flutter precache
      # - flutter doctor
      # - node -v
      # - npm -v

  pre_build:
    commands:
      # - echo "Fetching dependencies..."
      # - flutter clean
      # - flutter pub get
      # - flutter pub run build_runner build

      # - echo "Installing npm packages..."
      # - npm install

  build:
    commands:
      - echo "Deploy LambdaAPI ..."
      - cd infra
      - npm install
      - cdk deploy DeploymentStack-${BRANCH_NAME} --context branchName=$BRANCH_NAME

      # - echo "Building for web..."
      # - flutter build web --base-href /`echo $BRANCH_NAME`/
# artifacts:
#   files:
#     - '**/*'
#   base-directory: 'build/web'
