version: 0.2

phases:
  install:
    commands:
      - echo "Installing Flutter..."
      - git clone https://github.com/flutter/flutter.git -b stable
      - export PATH="$PATH:`pwd`/flutter/bin"
      - flutter precache
      - flutter doctor

      - echo "Installing Node.js..."
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      - source ~/.nvm/nvm.sh
      - nvm install node
      - node -v
      - npm -v

  pre_build:
    commands:
      - echo "Fetching dependencies..."
      - flutter clean
      - flutter pub get
      - flutter pub run build_runner build

      - echo "Installing npm packages..."
      - npm install

  build:
    commands:
      - echo "Building for web..."
      - flutter build web

artifacts:
  files:
    - 'build/web/**/*'
  base-directory: 'build/web'
