version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: app_buildspec
      ignore-failure: false
      buildspec: app_buildspec.yaml

    - identifier: api_buildspec
      ignore-failure: false
      buildspec: api_buildspec.yaml

phases:
  build:
    commands:
      - echo "Running batch build..."
